# Generated by Django 5.2.4 on 2025-09-01 16:49

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Diamond Champion', 'Diamond Champion'), ('Pearl Pioneer', 'Pearl Pioneer'), ('Emerald Guardian', 'Emerald Guardian'), ('Ruby Defender', 'Ruby Defender'), ('Sapphire Scout', 'Sapphire Scout'), ('Amethyst Advocate', 'Amethyst Advocate')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('last_ndvi', models.FloatField()),
                ('last_date_checked', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NDVIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_values', models.FloatField()),
                ('image_taken_date', models.DateField(auto_now_add=True)),
                ('image_url', models.URLField(max_length=500)),
                ('forest_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forest_NDVI_Records', to='terratrac.forestarea')),
            ],
        ),
        migrations.CreateModel(
            name='TerratracUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_num', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, db_index=True, to='terratrac.badge')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
