# Generated by Django 5.2.4 on 2025-09-01 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terratrac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(choices=[('Pearl Pioneer', 'Pearl Pioneer'), ('Ruby Defender', 'Ruby Defender'), ('Sapphire Scout', 'Sapphire Scout'), ('Diamond Champion', 'Diamond Champion'), ('Emerald Guardian', 'Emerald Guardian'), ('Amethyst Advocate', 'Amethyst Advocate')], max_length=100),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_on', models.DateField(auto_created=True)),
                ('alert_type', models.CharField(choices=[('Afforestation', 'afforestation'), ('Deforestation', 'deforestation')], db_index=True, max_length=50)),
                ('change_value', models.FloatField()),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Verified', 'Verified')], db_index=True, max_length=50)),
                ('forest_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forest_alerts', to='terratrac.forestarea')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateField(auto_created=True)),
                ('image', models.ImageField(upload_to='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('linked_alert', models.ManyToManyField(to='terratrac.alert')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_issued_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('notes', models.TextField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terratrac.alert')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verifications', to='terratrac.terratracuser')),
            ],
        ),
    ]
