# Generated by Django 5.2.4 on 2025-09-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terratrac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='forest_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forests', to='terratrac.forestarea'),
        ),
    ]
