# Generated by Django 5.2.4 on 2025-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terratrac', '0002_communityreport_forest_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreport',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
