# Generated by Django 5.2.4 on 2025-09-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terratrac', '0002_alter_badge_name_alert_communityreport_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Deforestation', 'deforestation'), ('Afforestation', 'afforestation')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(choices=[('Diamond Champion', 'Diamond Champion'), ('Pearl Pioneer', 'Pearl Pioneer'), ('Amethyst Advocate', 'Amethyst Advocate'), ('Emerald Guardian', 'Emerald Guardian'), ('Sapphire Scout', 'Sapphire Scout'), ('Ruby Defender', 'Ruby Defender')], max_length=100),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_issued_reports', to='terratrac.terratracuser'),
        ),
    ]
